# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180213_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creator_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='creator_id',
            field=models.IntegerField(),
        ),
    ]
